name: Deploy to Production Enviroment

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13
    
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Builds the angular code
      - name: Build Angular
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.tonoli.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          allow: network.host, security.insecure
          network: host
          context: .
          push: true
          tags: |
            docker.tonoli.net/api:latest
            docker.tonoli.net/api:0.0.1

